spring:
  application:
    name: admin_system
  datasource:
    url: jdbc:mysql://localhost:3306/admin_system
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
